services:
  db:
    image: postgres:17
    container_name: previ_db
    environment:
      POSTGRES_DB: previ
      POSTGRES_USER: previ
      POSTGRES_PASSWORD: previ
    ports:
      - '5432:5432'
    volumes:
      - previ_pgdata:/var/lib/postgresql/data

volumes:
  previ_pgdata:
